### PR TITLE
chore: release main

### PR DESCRIPTION
**Pull request by zone-live**
:robot: I have created a release *beep* *boop*
---

<details><summary>@metamask-institutional/custody-controller: 0.2.19</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @metamask-institutional/custody-keyring bumped from ^1.0.7 to ^1.0.8
    * @metamask-institutional/sdk bumped from ^0.1.23 to ^0.1.24
</details>

<details><summary>@metamask-institutional/custody-keyring: 1.0.8</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @metamask-institutional/sdk bumped from ^0.1.23 to ^0.1.24
</details>

<details><summary>@metamask-institutional/extension: 0.3.13</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @metamask-institutional/custody-controller bumped from ^0.2.18 to ^0.2.19
    * @metamask-institutional/custody-keyring bumped from ^1.0.7 to ^1.0.8
    * @metamask-institutional/sdk bumped from ^0.1.23 to ^0.1.24
    * @metamask-institutional/transaction-update bumped from ^0.1.33 to ^0.1.34
</details>

<details><summary>@metamask-institutional/institutional-features: 1.2.11</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @metamask-institutional/custody-keyring bumped from ^1.0.7 to ^1.0.8
</details>

<details><summary>sdk: 0.1.24</summary>

### Bug Fixes

* only create an ITR event if the custodian returns a URL where the user can go ([#608](https://github.com/consensys-vertical-apps/metamask-institutional/issues/608)) ([dc17ed2](https://github.com/consensys-vertical-apps/metamask-institutional/commit/dc17ed2e60b8cf44d3b3d49e5ccac5c7e9e51959))
</details>

<details><summary>@metamask-institutional/transaction-update: 0.1.34</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @metamask-institutional/custody-keyring bumped from ^1.0.7 to ^1.0.8
    * @metamask-institutional/sdk bumped from ^0.1.23 to ^0.1.24
    * @metamask-institutional/websocket-client bumped from ^0.1.35 to ^0.1.36
</details>

<details><summary>@metamask-institutional/websocket-client: 0.1.36</summary>

### Dependencies

* The following workspace dependencies were updated
  * dependencies
    * @metamask-institutional/custody-keyring bumped from ^1.0.7 to ^1.0.8
    * @metamask-institutional/sdk bumped from ^0.1.23 to ^0.1.24
</details>

---
This PR was generated with [Release Please](https://github.com/googleapis/release-please). See [documentation](https://github.com/googleapis/release-please#release-please).

### CODE REVIEW

**Review by shane-t — APPROVED** [review]

**Comment by zone-live** [comment]
:robot: Release is at https://github.com/consensys-vertical-apps/metamask-institutional/releases/tag/custody-controller-v0.2.19 :sunflower:

**Comment by zone-live** [comment]
:robot: Release is at https://github.com/consensys-vertical-apps/metamask-institutional/releases/tag/custody-keyring-v1.0.8 :sunflower:

**Comment by zone-live** [comment]
:robot: Release is at https://github.com/consensys-vertical-apps/metamask-institutional/releases/tag/institutional-features-v1.2.11 :sunflower:

**Comment by zone-live** [comment]
:robot: Release is at https://github.com/consensys-vertical-apps/metamask-institutional/releases/tag/sdk-v0.1.24 :sunflower:

**Comment by zone-live** [comment]
:robot: Release is at https://github.com/consensys-vertical-apps/metamask-institutional/releases/tag/transaction-update-v0.1.34 :sunflower:

**Comment by zone-live** [comment]
:robot: Release is at https://github.com/consensys-vertical-apps/metamask-institutional/releases/tag/websocket-client-v0.1.36 :sunflower:

**Comment by zone-live** [comment]
:robot: Release is at https://github.com/consensys-vertical-apps/metamask-institutional/releases/tag/extension-v0.3.13 :sunflower:

**Pull request merged**
